# Enable C++ and STL support 
CONFIG_CPP=y 
CONFIG_CPP_EXCEPTIONS=y 
CONFIG_CPP_RTTI=y 
CONFIG_STD_CPP23=y 
CONFIG_GLIBCXX_LIBCPP=y 
CONFIG_NEWLIB_LIBC=y 
CONFIG_NEWLIB_LIBC_NANO=n 

# System 
CONFIG_FPU=y 
CONFIG_FPU_SHARING=y 
CONFIG_THREAD_ANALYZER=y

# USB (new)
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y

# Enable logging
CONFIG_LOG=y
CONFIG_SENSOR_LOG_LEVEL_WRN=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_LOG_BUFFER_SIZE=8192
# Enable console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG_PRINTK=n
CONFIG_SHELL_LOG_BACKEND=n
